# Simplified workflow for ES Modules deployment
name: Build and deploy Node.js app to Azure Web App - Researchcollab
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: npm install
        run: npm install
      - name: Create web.config
        run: |
          echo '<?xml version="1.0" encoding="utf-8"?>' > web.config
          echo '<configuration>' >> web.config
          echo '  <system.webServer>' >> web.config
          echo '    <webSocket enabled="false" />' >> web.config
          echo '    <handlers>' >> web.config
          echo '      <add name="iisnode" path="src/server.js" verb="*" modules="iisnode" />' >> web.config
          echo '    </handlers>' >> web.config
          echo '    <rewrite>' >> web.config
          echo '      <rules>' >> web.config
          echo '        <rule name="DynamicContent">' >> web.config
          echo '          <match url="/*" />' >> web.config
          echo '          <action type="Rewrite" url="src/server.js" />' >> web.config
          echo '        </rule>' >> web.config
          echo '      </rules>' >> web.config
          echo '    </rewrite>' >> web.config
          echo '    <iisnode nodeProcessCommandLine="node" />' >> web.config
          echo '  </system.webServer>' >> web.config
          echo '</configuration>' >> web.config
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4A4A764D929B47B28BF0063F73052F32 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FAC2335600414AE98E34E5FD7688388B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2B4275E346D2469C9CCADE25D8F2BE74 }}
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Researchcollab'
          slot-name: 'Production'
          package: .
